---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Remove localtime
  file: path=/etc/localtime state=absent
  tags: ntp
 
- name: Make symlink to JST
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644
  tags: ntp

- name: Be sure ntp is installed
  yum: pkg=ntp state=installed
  tags: ntp

- name: Be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: Be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

- name: Make timezone persistence
  template: src=clock.j2 dest=/etc/sysconfig/clock
  tags: ntp

- name: Ensure yum packages are installed (RedHat).
  yum: >
    name={{ item }}
    state=installed
    enablerepo={{ yum_enablerepo }}
  with_items: yum_packages
  when: ansible_os_family == 'RedHat'
